"""add evidence embeddings

Revision ID: b15247332768
Revises: c4f8a9d2e6b1
Create Date: 2026-09-25 12:01:42.721317

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.models.evidence_embedding import EmbeddingVector


# revision identifiers, used by Alembic.
revision: str = 'b15247332768'
down_revision: Union[str, Sequence[str], None] = 'c4f8a9d2e6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Unbounded vector: feature-hash-v1 is 256-d and text-embedding-3-small
    # without a dimensions argument is 1536-d. vector(N) cannot store both.
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('evidence_embeddings',
    sa.Column('evidence_id', sa.String(length=250), nullable=False),
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('embedding', EmbeddingVector(), nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=200), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('embedding_dimensions > 0', name=op.f('ck_evidence_embeddings_embedding_dimensions_positive')),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], name=op.f('fk_evidence_embeddings_candidate_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_embeddings')),
    sa.UniqueConstraint('evidence_id', 'embedding_model', 'content_hash', name='uq_evidence_embeddings_cache_key')
    )
    with op.batch_alter_table('evidence_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_embeddings_candidate_profile_id'), ['candidate_profile_id'], unique=False)
        batch_op.create_index('ix_evidence_embeddings_profile_model_dims', ['candidate_profile_id', 'embedding_model', 'embedding_dimensions'], unique=False)

    # SQLite has no vector_dims(); CI migrates SQLite. Enforce the width match
    # in PostgreSQL only. PgVectorStore also checks the length before insert.
    if op.get_bind().dialect.name == "postgresql":
        op.create_check_constraint(
            "vector_dims",
            "evidence_embeddings",
            "vector_dims(embedding) = embedding_dimensions",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_embeddings_profile_model_dims')
        batch_op.drop_index(batch_op.f('ix_evidence_embeddings_candidate_profile_id'))

    op.drop_table('evidence_embeddings')
    # ### end Alembic commands ###
