"""initial recruiter ready schema

Revision ID: e18c8cbf35a5
Revises:
Create Date: 2026-08-09 22:07:13.249235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18c8cbf35a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('raw_title', sa.String(length=250), nullable=False),
    sa.Column('company_name', sa.String(length=250), nullable=True),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('source_platform', sa.String(length=100), nullable=True),
    sa.Column('job_url', sa.String(length=1000), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('workplace_type', sa.String(length=100), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max', name=op.f('ck_job_descriptions_salary_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_descriptions'))
    )
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_descriptions_company_name'), ['company_name'], unique=False)
        batch_op.create_index('ix_job_descriptions_company_title', ['company_name', 'raw_title'], unique=False)
        batch_op.create_index('ix_job_descriptions_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_descriptions_employment_type'), ['employment_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_descriptions_location'), ['location'], unique=False)
        batch_op.create_index('ix_job_descriptions_platform_location', ['source_platform', 'location'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_descriptions_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_descriptions_raw_title'), ['raw_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_descriptions_source_platform'), ['source_platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_descriptions_workplace_type'), ['workplace_type'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('candidate_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('headline', sa.String(length=250), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_candidate_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_profiles'))
    )
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_profiles_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_profiles_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_profiles_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('job_analyses',
    sa.Column('job_description_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('analyzer_name', sa.String(length=100), nullable=False),
    sa.Column('analyzer_version', sa.String(length=50), nullable=False),
    sa.Column('normalized_title', sa.String(length=250), nullable=False),
    sa.Column('seniority_level', sa.String(length=100), nullable=False),
    sa.Column('estimated_years_min', sa.Integer(), nullable=True),
    sa.Column('estimated_years_max', sa.Integer(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('preferred_skills', sa.JSON(), nullable=False),
    sa.Column('required_technologies', sa.JSON(), nullable=False),
    sa.Column('preferred_technologies', sa.JSON(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('qualifications', sa.JSON(), nullable=False),
    sa.Column('soft_skills', sa.JSON(), nullable=False),
    sa.Column('domain_keywords', sa.JSON(), nullable=False),
    sa.Column('ats_keywords', sa.JSON(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('missing_information', sa.JSON(), nullable=False),
    sa.Column('job_summary', sa.Text(), nullable=False),
    sa.Column('match_relevant_signals', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('estimated_years_max IS NULL OR estimated_years_max >= 0', name=op.f('ck_job_analyses_estimated_years_max_non_negative')),
    sa.CheckConstraint('estimated_years_min IS NULL OR estimated_years_max IS NULL OR estimated_years_min <= estimated_years_max', name=op.f('ck_job_analyses_estimated_years_range')),
    sa.CheckConstraint('estimated_years_min IS NULL OR estimated_years_min >= 0', name=op.f('ck_job_analyses_estimated_years_min_non_negative')),
    sa.CheckConstraint('revision > 0', name=op.f('ck_job_analyses_revision_positive')),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], name=op.f('fk_job_analyses_job_description_id_job_descriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_analyses'))
    )
    with op.batch_alter_table('job_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_job_analyses_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_job_analyses_description_revision', ['job_description_id', 'revision'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_analyses_job_description_id'), ['job_description_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_analyses_normalized_title'), ['normalized_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_analyses_seniority_level'), ['seniority_level'], unique=False)
        batch_op.create_index('ix_job_analyses_title_seniority', ['normalized_title', 'seniority_level'], unique=False)

    op.create_table('career_goals',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('preferred_industries', sa.JSON(), nullable=False),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=False),
    sa.Column('remote_preference', sa.Enum('REMOTE', 'HYBRID', 'ONSITE', 'FLEXIBLE', name='remotepreference', native_enum=False), nullable=False),
    sa.Column('relocation_preference', sa.Enum('WILLING', 'NOT_WILLING', 'CONDITIONAL', name='relocationpreference', native_enum=False), nullable=False),
    sa.Column('geographic_preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max', name=op.f('ck_career_goals_salary_range')),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_career_goals_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_goals')),
    sa.UniqueConstraint('profile_id', name=op.f('uq_career_goals_profile_id'))
    )
    with op.batch_alter_table('career_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_goals_profile_id'), ['profile_id'], unique=False)

    op.create_table('certifications',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('issuing_organization', sa.String(length=250), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=250), nullable=True),
    sa.Column('credential_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('issue_date IS NULL OR expiration_date IS NULL OR issue_date <= expiration_date', name=op.f('ck_certifications_date_range')),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_certifications_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications'))
    )
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certifications_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index('ix_certifications_profile_name', ['profile_id', 'name'], unique=False)

    op.create_table('education',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('institution', sa.String(length=250), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=False),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR start_date <= end_date', name=op.f('ck_education_date_range')),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_education_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education'))
    )
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_education_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index('ix_education_profile_institution', ['profile_id', 'institution'], unique=False)

    op.create_table('preferences',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('resume_style', sa.Enum('ATS_FOCUSED', 'CLASSIC', 'MINIMAL', 'MODERN', name='resumestyle', native_enum=False), nullable=False),
    sa.Column('resume_preferences', sa.JSON(), nullable=False),
    sa.Column('application_preferences', sa.JSON(), nullable=False),
    sa.Column('communication_preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_preferences_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preferences')),
    sa.UniqueConstraint('profile_id', name=op.f('uq_preferences_profile_id'))
    )
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preferences_profile_id'), ['profile_id'], unique=False)

    op.create_table('projects',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('outcomes', sa.JSON(), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR start_date <= end_date', name=op.f('ck_projects_date_range')),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_projects_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index('ix_projects_profile_title', ['profile_id', 'title'], unique=False)

    op.create_table('resume_analyses',
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('overall_match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('keyword_match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('skills_match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('technology_match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('experience_match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('project_match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('education_match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('matched_keywords', sa.JSON(), nullable=False),
    sa.Column('missing_keywords', sa.JSON(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('matched_technologies', sa.JSON(), nullable=False),
    sa.Column('missing_technologies', sa.JSON(), nullable=False),
    sa.Column('relevant_projects', sa.JSON(), nullable=False),
    sa.Column('relevant_experiences', sa.JSON(), nullable=False),
    sa.Column('relevant_education', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('gap_analysis', sa.JSON(), nullable=False),
    sa.Column('tailoring_recommendations', sa.JSON(), nullable=False),
    sa.Column('truthfulness_warnings', sa.JSON(), nullable=False),
    sa.Column('suggested_resume_summary', sa.Text(), nullable=False),
    sa.Column('suggested_resume_sections', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('education_match_score >= 0 AND education_match_score <= 100', name=op.f('ck_resume_analyses_education_match_score_range')),
    sa.CheckConstraint('experience_match_score >= 0 AND experience_match_score <= 100', name=op.f('ck_resume_analyses_experience_match_score_range')),
    sa.CheckConstraint('keyword_match_score >= 0 AND keyword_match_score <= 100', name=op.f('ck_resume_analyses_keyword_match_score_range')),
    sa.CheckConstraint('overall_match_score >= 0 AND overall_match_score <= 100', name=op.f('ck_resume_analyses_overall_match_score_range')),
    sa.CheckConstraint('project_match_score >= 0 AND project_match_score <= 100', name=op.f('ck_resume_analyses_project_match_score_range')),
    sa.CheckConstraint('skills_match_score >= 0 AND skills_match_score <= 100', name=op.f('ck_resume_analyses_skills_match_score_range')),
    sa.CheckConstraint('technology_match_score >= 0 AND technology_match_score <= 100', name=op.f('ck_resume_analyses_technology_match_score_range')),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], name=op.f('fk_resume_analyses_candidate_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_analysis_id'], ['job_analyses.id'], name=op.f('fk_resume_analyses_job_analysis_id_job_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_analyses'))
    )
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_resume_analyses_candidate_job_created', ['candidate_profile_id', 'job_analysis_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_analyses_candidate_profile_id'), ['candidate_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_analyses_job_analysis_id'), ['job_analysis_id'], unique=False)

    op.create_table('resume_versions',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source_profile_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_resume_versions_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_versions'))
    )
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.create_index('ix_resume_versions_profile_created', ['profile_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_versions_profile_id'), ['profile_id'], unique=False)

    op.create_table('skills',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('self_rating', sa.Integer(), nullable=False),
    sa.Column('years_of_experience', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('self_rating >= 1 AND self_rating <= 5', name=op.f('ck_skills_self_rating_range')),
    sa.CheckConstraint('years_of_experience >= 0', name=op.f('ck_skills_years_of_experience_non_negative')),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_skills_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('profile_id', 'name', name=op.f('uq_skills_profile_id'))
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)
        batch_op.create_index('ix_skills_profile_category', ['profile_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_profile_id'), ['profile_id'], unique=False)

    op.create_table('work_experiences',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('company', sa.String(length=250), nullable=False),
    sa.Column('job_title', sa.String(length=250), nullable=False),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR start_date <= end_date', name=op.f('ck_work_experiences_date_range')),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_work_experiences_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_experiences'))
    )
    with op.batch_alter_table('work_experiences', schema=None) as batch_op:
        batch_op.create_index('ix_work_experiences_profile_company', ['profile_id', 'company'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_experiences_profile_id'), ['profile_id'], unique=False)

    op.create_table('application_history',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('resume_version_id', sa.Uuid(), nullable=True),
    sa.Column('job_description_id', sa.Uuid(), nullable=True),
    sa.Column('company', sa.String(length=250), nullable=False),
    sa.Column('job_title', sa.String(length=250), nullable=False),
    sa.Column('job_url', sa.String(length=500), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('NOT_APPLIED', 'SAVED', 'APPLIED', 'INTERVIEWING', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], name=op.f('fk_application_history_job_description_id_job_descriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['candidate_profiles.id'], name=op.f('fk_application_history_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], name=op.f('fk_application_history_resume_version_id_resume_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_history'))
    )
    with op.batch_alter_table('application_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_history_job_description_id'), ['job_description_id'], unique=False)
        batch_op.create_index('ix_application_history_profile_company', ['profile_id', 'company'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_history_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index('ix_application_history_profile_status', ['profile_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_history_resume_version_id'), ['resume_version_id'], unique=False)

    op.create_table('resume_drafts',
    sa.Column('resume_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('target_role', sa.String(length=250), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('skills_section', sa.JSON(), nullable=False),
    sa.Column('experience_section', sa.JSON(), nullable=False),
    sa.Column('projects_section', sa.JSON(), nullable=False),
    sa.Column('education_section', sa.JSON(), nullable=False),
    sa.Column('certifications_section', sa.JSON(), nullable=False),
    sa.Column('ats_keywords_used', sa.JSON(), nullable=False),
    sa.Column('omitted_keywords', sa.JSON(), nullable=False),
    sa.Column('truthfulness_notes', sa.JSON(), nullable=False),
    sa.Column('grounding_manifest', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], name=op.f('fk_resume_drafts_candidate_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_analysis_id'], ['job_analyses.id'], name=op.f('fk_resume_drafts_job_analysis_id_job_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_analysis_id'], ['resume_analyses.id'], name=op.f('fk_resume_drafts_resume_analysis_id_resume_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_drafts'))
    )
    with op.batch_alter_table('resume_drafts', schema=None) as batch_op:
        batch_op.create_index('ix_resume_drafts_analysis_created', ['resume_analysis_id', 'created_at'], unique=False)
        batch_op.create_index('ix_resume_drafts_candidate_created', ['candidate_profile_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_drafts_candidate_profile_id'), ['candidate_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_drafts_job_analysis_id'), ['job_analysis_id'], unique=False)
        batch_op.create_index('ix_resume_drafts_job_created', ['job_analysis_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_drafts_resume_analysis_id'), ['resume_analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_drafts_status'), ['status'], unique=False)

    op.create_table('generated_documents',
    sa.Column('resume_draft_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('output_format', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=2000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('generation_status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], name=op.f('fk_generated_documents_candidate_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_analysis_id'], ['job_analyses.id'], name=op.f('fk_generated_documents_job_analysis_id_job_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_draft_id'], ['resume_drafts.id'], name=op.f('fk_generated_documents_resume_draft_id_resume_drafts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_documents'))
    )
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.create_index('ix_generated_documents_candidate_created', ['candidate_profile_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_candidate_profile_id'), ['candidate_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_checksum'), ['checksum'], unique=False)
        batch_op.create_index('ix_generated_documents_draft_created', ['resume_draft_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_generation_status'), ['generation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_job_analysis_id'), ['job_analysis_id'], unique=False)
        batch_op.create_index('ix_generated_documents_job_created', ['job_analysis_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_output_format'), ['output_format'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_resume_draft_id'), ['resume_draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_documents_template_name'), ['template_name'], unique=False)

    op.create_table('application_records',
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_description_id', sa.Uuid(), nullable=True),
    sa.Column('job_analysis_id', sa.Uuid(), nullable=True),
    sa.Column('generated_document_id', sa.Uuid(), nullable=True),
    sa.Column('company_name', sa.String(length=250), nullable=False),
    sa.Column('role_title', sa.String(length=250), nullable=False),
    sa.Column('company_email', sa.String(length=320), nullable=True),
    sa.Column('job_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evidence_coverage_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('not_applied', 'saved', 'applied', 'interviewing', 'rejected')", name=op.f('ck_application_records_status_supported')),
    sa.CheckConstraint('evidence_coverage_score IS NULL OR (evidence_coverage_score >= 0 AND evidence_coverage_score <= 100)', name=op.f('ck_application_records_evidence_coverage_score_range')),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], name=op.f('fk_application_records_candidate_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_document_id'], ['generated_documents.id'], name=op.f('fk_application_records_generated_document_id_generated_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_analysis_id'], ['job_analyses.id'], name=op.f('fk_application_records_job_analysis_id_job_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], name=op.f('fk_application_records_job_description_id_job_descriptions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_records'))
    )
    with op.batch_alter_table('application_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_records_applied_at'), ['applied_at'], unique=False)
        batch_op.create_index('ix_application_records_candidate_company', ['candidate_profile_id', 'company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_records_candidate_profile_id'), ['candidate_profile_id'], unique=False)
        batch_op.create_index('ix_application_records_candidate_role', ['candidate_profile_id', 'role_title'], unique=False)
        batch_op.create_index('ix_application_records_candidate_status', ['candidate_profile_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_records_company_email'), ['company_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_records_generated_document_id'), ['generated_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_records_job_analysis_id'), ['job_analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_records_job_description_id'), ['job_description_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_records_status'), ['status'], unique=False)

    op.create_table('career_analysis_runs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_description_id', sa.Uuid(), nullable=True),
    sa.Column('job_analysis_id', sa.Uuid(), nullable=True),
    sa.Column('resume_analysis_id', sa.Uuid(), nullable=True),
    sa.Column('resume_draft_id', sa.Uuid(), nullable=True),
    sa.Column('application_record_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('structured_requirements', sa.JSON(), nullable=False),
    sa.Column('evidence_matches', sa.JSON(), nullable=False),
    sa.Column('evidence_coverage_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stage_results', sa.JSON(), nullable=False),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('estimated_cost_usd >= 0', name=op.f('ck_career_analysis_runs_estimated_cost_non_negative')),
    sa.CheckConstraint('evidence_coverage_score IS NULL OR (evidence_coverage_score >= 0 AND evidence_coverage_score <= 100)', name=op.f('ck_career_analysis_runs_evidence_coverage_score_range')),
    sa.ForeignKeyConstraint(['application_record_id'], ['application_records.id'], name=op.f('fk_career_analysis_runs_application_record_id_application_records'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], name=op.f('fk_career_analysis_runs_candidate_profile_id_candidate_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_analysis_id'], ['job_analyses.id'], name=op.f('fk_career_analysis_runs_job_analysis_id_job_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], name=op.f('fk_career_analysis_runs_job_description_id_job_descriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_analysis_id'], ['resume_analyses.id'], name=op.f('fk_career_analysis_runs_resume_analysis_id_resume_analyses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_draft_id'], ['resume_drafts.id'], name=op.f('fk_career_analysis_runs_resume_draft_id_resume_drafts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_career_analysis_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_analysis_runs'))
    )
    with op.batch_alter_table('career_analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_analysis_runs_application_record_id'), ['application_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_career_analysis_runs_candidate_profile_id'), ['candidate_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_career_analysis_runs_job_analysis_id'), ['job_analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_career_analysis_runs_job_description_id'), ['job_description_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_career_analysis_runs_resume_analysis_id'), ['resume_analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_career_analysis_runs_resume_draft_id'), ['resume_draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_career_analysis_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_career_analysis_runs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_career_analysis_runs_user_candidate_created', ['user_id', 'candidate_profile_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_career_analysis_runs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('career_analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_analysis_runs_user_id'))
        batch_op.drop_index('ix_career_analysis_runs_user_candidate_created')
        batch_op.drop_index('ix_career_analysis_runs_status_created')
        batch_op.drop_index(batch_op.f('ix_career_analysis_runs_status'))
        batch_op.drop_index(batch_op.f('ix_career_analysis_runs_resume_draft_id'))
        batch_op.drop_index(batch_op.f('ix_career_analysis_runs_resume_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_career_analysis_runs_job_description_id'))
        batch_op.drop_index(batch_op.f('ix_career_analysis_runs_job_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_career_analysis_runs_candidate_profile_id'))
        batch_op.drop_index(batch_op.f('ix_career_analysis_runs_application_record_id'))

    op.drop_table('career_analysis_runs')
    with op.batch_alter_table('application_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_records_status'))
        batch_op.drop_index(batch_op.f('ix_application_records_job_description_id'))
        batch_op.drop_index(batch_op.f('ix_application_records_job_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_application_records_generated_document_id'))
        batch_op.drop_index(batch_op.f('ix_application_records_company_email'))
        batch_op.drop_index('ix_application_records_candidate_status')
        batch_op.drop_index('ix_application_records_candidate_role')
        batch_op.drop_index(batch_op.f('ix_application_records_candidate_profile_id'))
        batch_op.drop_index('ix_application_records_candidate_company')
        batch_op.drop_index(batch_op.f('ix_application_records_applied_at'))

    op.drop_table('application_records')
    with op.batch_alter_table('generated_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_documents_template_name'))
        batch_op.drop_index(batch_op.f('ix_generated_documents_resume_draft_id'))
        batch_op.drop_index(batch_op.f('ix_generated_documents_output_format'))
        batch_op.drop_index('ix_generated_documents_job_created')
        batch_op.drop_index(batch_op.f('ix_generated_documents_job_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_generated_documents_generation_status'))
        batch_op.drop_index('ix_generated_documents_draft_created')
        batch_op.drop_index(batch_op.f('ix_generated_documents_checksum'))
        batch_op.drop_index(batch_op.f('ix_generated_documents_candidate_profile_id'))
        batch_op.drop_index('ix_generated_documents_candidate_created')

    op.drop_table('generated_documents')
    with op.batch_alter_table('resume_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_resume_drafts_resume_analysis_id'))
        batch_op.drop_index('ix_resume_drafts_job_created')
        batch_op.drop_index(batch_op.f('ix_resume_drafts_job_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_resume_drafts_candidate_profile_id'))
        batch_op.drop_index('ix_resume_drafts_candidate_created')
        batch_op.drop_index('ix_resume_drafts_analysis_created')

    op.drop_table('resume_drafts')
    with op.batch_alter_table('application_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_history_resume_version_id'))
        batch_op.drop_index('ix_application_history_profile_status')
        batch_op.drop_index(batch_op.f('ix_application_history_profile_id'))
        batch_op.drop_index('ix_application_history_profile_company')
        batch_op.drop_index(batch_op.f('ix_application_history_job_description_id'))

    op.drop_table('application_history')
    with op.batch_alter_table('work_experiences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_experiences_profile_id'))
        batch_op.drop_index('ix_work_experiences_profile_company')

    op.drop_table('work_experiences')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_profile_id'))
        batch_op.drop_index('ix_skills_profile_category')
        batch_op.drop_index(batch_op.f('ix_skills_category'))

    op.drop_table('skills')
    with op.batch_alter_table('resume_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_versions_profile_id'))
        batch_op.drop_index('ix_resume_versions_profile_created')

    op.drop_table('resume_versions')
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_analyses_job_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_resume_analyses_candidate_profile_id'))
        batch_op.drop_index('ix_resume_analyses_candidate_job_created')

    op.drop_table('resume_analyses')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_profile_title')
        batch_op.drop_index(batch_op.f('ix_projects_profile_id'))

    op.drop_table('projects')
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preferences_profile_id'))

    op.drop_table('preferences')
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_index('ix_education_profile_institution')
        batch_op.drop_index(batch_op.f('ix_education_profile_id'))

    op.drop_table('education')
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_index('ix_certifications_profile_name')
        batch_op.drop_index(batch_op.f('ix_certifications_profile_id'))

    op.drop_table('certifications')
    with op.batch_alter_table('career_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_goals_profile_id'))

    op.drop_table('career_goals')
    with op.batch_alter_table('job_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_job_analyses_title_seniority')
        batch_op.drop_index(batch_op.f('ix_job_analyses_seniority_level'))
        batch_op.drop_index(batch_op.f('ix_job_analyses_normalized_title'))
        batch_op.drop_index(batch_op.f('ix_job_analyses_job_description_id'))
        batch_op.drop_index('ix_job_analyses_description_revision')
        batch_op.drop_index('ix_job_analyses_created_at')

    op.drop_table('job_analyses')
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_location'))
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_full_name'))
        batch_op.drop_index(batch_op.f('ix_candidate_profiles_email'))

    op.drop_table('candidate_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('job_descriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_descriptions_workplace_type'))
        batch_op.drop_index(batch_op.f('ix_job_descriptions_source_platform'))
        batch_op.drop_index(batch_op.f('ix_job_descriptions_raw_title'))
        batch_op.drop_index(batch_op.f('ix_job_descriptions_posted_at'))
        batch_op.drop_index('ix_job_descriptions_platform_location')
        batch_op.drop_index(batch_op.f('ix_job_descriptions_location'))
        batch_op.drop_index(batch_op.f('ix_job_descriptions_employment_type'))
        batch_op.drop_index('ix_job_descriptions_created_at')
        batch_op.drop_index('ix_job_descriptions_company_title')
        batch_op.drop_index(batch_op.f('ix_job_descriptions_company_name'))

    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
